# Generated by Django 3.2.7 on 2021-09-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internetconsumption',
            name='consumption_date',
            field=models.DateTimeField(),
        ),
    ]
